server:
  port: 8082

spring:
  application:
    name: player-service
  datasource:
    url: jdbc:postgresql://localhost:5434/playerdb
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

## ????????? ??? Feign Client
#feign:
#  hystrix:
#    enabled: false
#
## ????????? ??? ?????????????? ? Auth Service (???? ??????????)
#auth-service:
#  url: http://localhost:8080
